remote_theme: papers-themes/hacker
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have ones
title: Bin.Liang's Blog
description: Sharing the interesting!

header_pages:
  - _pages/header/resume.html


